"""Atom-economy calculations for individual reactions and full routes."""

from __future__ import annotations

from collections import defaultdict, deque
from typing import Any

import numpy as np
from rdkit import Chem
from rdkit.Chem.Descriptors import HeavyAtomMolWt


def step_atom_economy(rxn_smiles: str | None) -> float:
    """
    Compute heavy-atom economy for one reaction SMILES.

    This helper is retained for quick reaction-level checks; the production
    green score uses `route_atom_economy`, which considers the complete route.
    """
    if not rxn_smiles or not isinstance(rxn_smiles, str):
        return np.nan

    parts = rxn_smiles.split(">")
    if len(parts) != 3:
        return np.nan

    reactant_part, _, product_part = parts
    reactants = [smiles for smiles in reactant_part.split(".") if smiles]
    products = [smiles for smiles in product_part.split(".") if smiles]
    if not reactants or not products:
        return np.nan

    def total_heavy_atom_mass(smiles_list: list[str]) -> float:
        total = 0.0
        for smiles in smiles_list:
            mol = Chem.MolFromSmiles(smiles)
            if mol is None:
                continue
            total += HeavyAtomMolWt(mol)
        return total

    reactant_mass = total_heavy_atom_mass(reactants)
    product_mass = total_heavy_atom_mass(products)
    if reactant_mass <= 0:
        return np.nan

    return float(min(1.0, max(0.0, product_mass / reactant_mass)))


def route_atom_economy(route_entry: dict[str, Any]) -> float:
    """
    Compute atom economy for the full route by dividing the heavy-atom mass of the root
    product by the sum of heavy-atom masses of the leaf reagents (molecules that are only
    consumed and never produced inside the tracker entry).
    """

    def _canonicalize(smiles: str | None) -> tuple[str | None, Chem.Mol | None]:
        if not smiles:
            return None, None
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return None, None
        canonical = Chem.MolToSmiles(mol, canonical=True, isomericSmiles=True)
        return canonical, mol

    def _split_reaction(rxn_smiles: str) -> tuple[list[str], list[str]]:
        parts = rxn_smiles.split(">")
        if len(parts) != 3:
            return [], []
        reactants = [segment for segment in parts[0].split(".") if segment]
        products = [segment for segment in parts[2].split(".") if segment]
        return reactants, products

    molecules: dict[int, dict[str, Any]] = {}
    reaction_nodes: list[dict[str, Any]] = []
    # Buckets let us match products from reaction SMILES back to molecule nodes
    # at the expected tree depth, even when several nodes have the same SMILES.
    buckets: dict[tuple[int, str], deque[int]] = defaultdict(deque)
    product_node_id: int | None = None

    for key, node in route_entry.items():
        if not (isinstance(key, str) and key.startswith("node_") and isinstance(node, dict)):
            continue
        try:
            node_id = int(key.split("_", 1)[1])
        except (IndexError, ValueError):
            continue
        depth = node.get("depth")
        if depth is None:
            continue
        if node.get("is_mol"):
            canonical, mol = _canonicalize(node.get("mol_smiles"))
            if canonical is None or mol is None:
                continue
            molecules[node_id] = {
                "depth": depth,
                "canonical": canonical,
                "mol": mol,
            }
            buckets[(depth, canonical)].append(node_id)
            if depth == 0 and product_node_id is None:
                product_node_id = node_id
        elif node.get("is_rxn"):
            rxn_smiles = node.get("rxn_smiles")
            if isinstance(rxn_smiles, str):
                reaction_nodes.append(
                    {
                        "depth": depth,
                        "rxn_smiles": rxn_smiles,
                    }
                )

    if not molecules or product_node_id is None:
        return np.nan

    produced: set[int] = set()
    # Mark molecule nodes that are generated by some reaction. The remaining
    # non-root molecules are the leaf starting materials used in the denominator.
    for rxn in sorted(reaction_nodes, key=lambda info: info.get("depth", 0)):
        depth = rxn.get("depth")
        rxn_smiles = rxn.get("rxn_smiles")
        if depth is None or not rxn_smiles:
            continue
        product_depth = depth - 1
        _, products = _split_reaction(rxn_smiles)
        for product in products:
            canonical, _ = _canonicalize(product)
            if canonical is None:
                continue
            queue = buckets.get((product_depth, canonical))
            if not queue:
                continue
            while queue:
                # Consume only one matching node per product occurrence so
                # duplicate molecules in the route are handled independently.
                node_id = queue.popleft()
                if node_id in produced:
                    continue
                produced.add(node_id)
                break

    leaf_ids = [node_id for node_id in molecules if node_id not in produced and node_id != product_node_id]
    if not leaf_ids:
        return np.nan

    reactant_mass = 0.0
    for node_id in leaf_ids:
        mol = molecules[node_id]["mol"]
        reactant_mass += HeavyAtomMolWt(mol)

    if reactant_mass <= 0:
        return np.nan

    product_mass = HeavyAtomMolWt(molecules[product_node_id]["mol"])
    return float(min(1.0, max(0.0, product_mass / reactant_mass)))
